import { GoogleGenAI } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  console.error("API Key is missing. Please check your environment variables.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY || '' });

export const extractCsvFromPdf = async (base64Pdf: string): Promise<string> => {
  try {
    // Using gemini-3-pro-preview as requested for complex reasoning
    // High thinking budget for thorough analysis of messy PDFs
    const response = await ai.models.generateContent({
      model: 'gemini-3-pro-preview',
      contents: {
        parts: [
          {
            inlineData: {
              mimeType: 'application/pdf',
              data: base64Pdf
            }
          },
          {
            text: `You are a PDF-to-Spreadsheet Extractor AI. Your job is to read the entire PDF I upload and convert all of its content into a clean, well-structured spreadsheet table.

RULES:
1. Extract ALL tables, rows, columns, and text-based data.
2. Reconstruct tables even if they are messy, tilted, scanned, or poorly formatted.
3. Remove duplicates, blank rows, repeated headers, watermarks, or irrelevant text.
4. Detect column headers automatically and standardize them.
5. Align all data into a clean row-and-column format suitable for Excel or Google Sheets.
6. If the PDF has multiple tables, combine them into separate labeled sections or merge if they share the same structure.
7. Output MUST be in pure CSV format — no commentary, no explanations, no markdown, no code blocks.
8. Only return the CSV content that can be exported directly into a spreadsheet.

If the PDF contains paragraphs, summarize into proper columns. If it contains forms, convert fields into columns. Normalize invoice line items.

Output ONLY raw CSV data.`
          }
        ]
      },
      config: {
        thinkingConfig: {
            thinkingBudget: 32768 // Max budget for gemini-3-pro-preview
        },
        // Note: We are NOT setting maxOutputTokens to allow full CSV generation
      }
    });

    const text = response.text;
    if (!text) {
      throw new Error("No content generated by the model.");
    }

    let cleanedText = text;
    // Extract content from code block if present (e.g., ```csv ... ```)
    const codeBlockMatch = text.match(/```(?:csv)?\n([\s\S]*?)```/);
    if (codeBlockMatch) {
      cleanedText = codeBlockMatch[1];
    } else {
        // Fallback cleanup if no code blocks but still has potential markdown artifacts
        cleanedText = text.replace(/```csv\n?/g, '').replace(/```\n?/g, '');
    }
    
    return cleanedText.trim();

  } catch (error: any) {
    console.error("Gemini API Error:", error);
    throw new Error(error.message || "Failed to process PDF");
  }
};

export const fileToBase64 = (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = () => {
      const result = reader.result as string;
      // Remove data URL prefix (e.g., "data:application/pdf;base64,")
      const base64 = result.split(',')[1];
      resolve(base64);
    };
    reader.onerror = error => reject(error);
  });
};